#Importing numpy

In [1]:
import numpy as np


In [2]:
#creating an array also consider it as vector 
arr1=np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
#it is 2dlist or consider it as matrix representaion
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3=np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr4=arr3.copy()
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#linspace return evenly spaced number over specified range
#here 1 and 10 are start,stop and 10 is included in the range
arr1=np.linspace(1,10,10)
arr1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
#here ndim represents a attribute that is why no ()
arr1
arr1.ndim

1

In [9]:
#This is an 3dim array
arr5=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr5

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# INDEXING, SLICING AND ITERATION

In [10]:
#here shape represents 2 rows ,2 columns, 2seprate matrix
arr5.shape

(2, 2, 2)

In [11]:
arr5.ndim

3

In [12]:
#here size is the no.of items
arr5.size

8

In [13]:
arr6=np.arange(24).reshape(6,4)
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
#Here we get the 2 and 3 column from the array as output
arr6[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [15]:
arr6[3:4,1:3]

array([[13, 14]])

# OPERATIONS

In [16]:
arr10=np.arange(6,12).reshape(2,3)
arr10

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
# Here min value is taken on the basics of column axis=0
arr10.min(axis=0)

array([6, 7, 8])

In [18]:
#Here min value is taken on the basics of row axis=1
arr10.min(axis=1)

array([6, 9])

In [19]:
arr10.sum()

51

In [20]:
# Here row wise sum is taken
arr10.sum(axis=1)

array([21, 30])